// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bike.proto

#ifndef PROTOBUF_bike_2eproto__INCLUDED
#define PROTOBUF_bike_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tutorial {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_bike_2eproto();
void protobuf_AssignDesc_bike_2eproto();
void protobuf_ShutdownFile_bike_2eproto();

class mobile_request;
class mobile_response;
class login_request;
class login_response;
class recharge_request;
class recharge_response;
class account_balance_request;
class account_balance_response;
class list_account_records_request;
class list_account_records_response;
class list_account_records_response_account_record;
class list_travel_records_request;
class list_travel_records_response;
class list_travel_records_response_travel_record;

// ===================================================================

class mobile_request : public ::google::protobuf::Message {
 public:
  mobile_request();
  virtual ~mobile_request();

  mobile_request(const mobile_request& from);

  inline mobile_request& operator=(const mobile_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mobile_request& default_instance();

  void Swap(mobile_request* other);

  // implements Message ----------------------------------------------

  mobile_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mobile_request& from);
  void MergeFrom(const mobile_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // @@protoc_insertion_point(class_scope:tutorial.mobile_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static mobile_request* default_instance_;
};
// -------------------------------------------------------------------

class mobile_response : public ::google::protobuf::Message {
 public:
  mobile_response();
  virtual ~mobile_response();

  mobile_response(const mobile_response& from);

  inline mobile_response& operator=(const mobile_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mobile_response& default_instance();

  void Swap(mobile_response* other);

  // implements Message ----------------------------------------------

  mobile_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mobile_response& from);
  void MergeFrom(const mobile_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // required int32 icode = 2;
  inline bool has_icode() const;
  inline void clear_icode();
  static const int kIcodeFieldNumber = 2;
  inline ::google::protobuf::int32 icode() const;
  inline void set_icode(::google::protobuf::int32 value);

  // optional string data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:tutorial.mobile_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_icode();
  inline void clear_has_icode();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 code_;
  ::google::protobuf::int32 icode_;
  ::std::string* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static mobile_response* default_instance_;
};
// -------------------------------------------------------------------

class login_request : public ::google::protobuf::Message {
 public:
  login_request();
  virtual ~login_request();

  login_request(const login_request& from);

  inline login_request& operator=(const login_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const login_request& default_instance();

  void Swap(login_request* other);

  // implements Message ----------------------------------------------

  login_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const login_request& from);
  void MergeFrom(const login_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // required int32 icode = 2;
  inline bool has_icode() const;
  inline void clear_icode();
  static const int kIcodeFieldNumber = 2;
  inline ::google::protobuf::int32 icode() const;
  inline void set_icode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.login_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();
  inline void set_has_icode();
  inline void clear_has_icode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;
  ::google::protobuf::int32 icode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static login_request* default_instance_;
};
// -------------------------------------------------------------------

class login_response : public ::google::protobuf::Message {
 public:
  login_response();
  virtual ~login_response();

  login_response(const login_response& from);

  inline login_response& operator=(const login_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const login_response& default_instance();

  void Swap(login_response* other);

  // implements Message ----------------------------------------------

  login_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const login_response& from);
  void MergeFrom(const login_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // @@protoc_insertion_point(class_scope:tutorial.login_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_desc();
  inline void clear_has_desc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  ::google::protobuf::int32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static login_response* default_instance_;
};
// -------------------------------------------------------------------

class recharge_request : public ::google::protobuf::Message {
 public:
  recharge_request();
  virtual ~recharge_request();

  recharge_request(const recharge_request& from);

  inline recharge_request& operator=(const recharge_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const recharge_request& default_instance();

  void Swap(recharge_request* other);

  // implements Message ----------------------------------------------

  recharge_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const recharge_request& from);
  void MergeFrom(const recharge_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // required int32 amount = 2;
  inline bool has_amount() const;
  inline void clear_amount();
  static const int kAmountFieldNumber = 2;
  inline ::google::protobuf::int32 amount() const;
  inline void set_amount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.recharge_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();
  inline void set_has_amount();
  inline void clear_has_amount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;
  ::google::protobuf::int32 amount_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static recharge_request* default_instance_;
};
// -------------------------------------------------------------------

class recharge_response : public ::google::protobuf::Message {
 public:
  recharge_response();
  virtual ~recharge_response();

  recharge_response(const recharge_response& from);

  inline recharge_response& operator=(const recharge_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const recharge_response& default_instance();

  void Swap(recharge_response* other);

  // implements Message ----------------------------------------------

  recharge_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const recharge_response& from);
  void MergeFrom(const recharge_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // required int32 balance = 3;
  inline bool has_balance() const;
  inline void clear_balance();
  static const int kBalanceFieldNumber = 3;
  inline ::google::protobuf::int32 balance() const;
  inline void set_balance(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.recharge_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_desc();
  inline void clear_has_desc();
  inline void set_has_balance();
  inline void clear_has_balance();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  ::google::protobuf::int32 code_;
  ::google::protobuf::int32 balance_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static recharge_response* default_instance_;
};
// -------------------------------------------------------------------

class account_balance_request : public ::google::protobuf::Message {
 public:
  account_balance_request();
  virtual ~account_balance_request();

  account_balance_request(const account_balance_request& from);

  inline account_balance_request& operator=(const account_balance_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const account_balance_request& default_instance();

  void Swap(account_balance_request* other);

  // implements Message ----------------------------------------------

  account_balance_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const account_balance_request& from);
  void MergeFrom(const account_balance_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // @@protoc_insertion_point(class_scope:tutorial.account_balance_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static account_balance_request* default_instance_;
};
// -------------------------------------------------------------------

class account_balance_response : public ::google::protobuf::Message {
 public:
  account_balance_response();
  virtual ~account_balance_response();

  account_balance_response(const account_balance_response& from);

  inline account_balance_response& operator=(const account_balance_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const account_balance_response& default_instance();

  void Swap(account_balance_response* other);

  // implements Message ----------------------------------------------

  account_balance_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const account_balance_response& from);
  void MergeFrom(const account_balance_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // required int32 balance = 3;
  inline bool has_balance() const;
  inline void clear_balance();
  static const int kBalanceFieldNumber = 3;
  inline ::google::protobuf::int32 balance() const;
  inline void set_balance(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.account_balance_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_desc();
  inline void clear_has_desc();
  inline void set_has_balance();
  inline void clear_has_balance();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  ::google::protobuf::int32 code_;
  ::google::protobuf::int32 balance_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static account_balance_response* default_instance_;
};
// -------------------------------------------------------------------

class list_account_records_request : public ::google::protobuf::Message {
 public:
  list_account_records_request();
  virtual ~list_account_records_request();

  list_account_records_request(const list_account_records_request& from);

  inline list_account_records_request& operator=(const list_account_records_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_account_records_request& default_instance();

  void Swap(list_account_records_request* other);

  // implements Message ----------------------------------------------

  list_account_records_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_account_records_request& from);
  void MergeFrom(const list_account_records_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // @@protoc_insertion_point(class_scope:tutorial.list_account_records_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_account_records_request* default_instance_;
};
// -------------------------------------------------------------------

class list_account_records_response_account_record : public ::google::protobuf::Message {
 public:
  list_account_records_response_account_record();
  virtual ~list_account_records_response_account_record();

  list_account_records_response_account_record(const list_account_records_response_account_record& from);

  inline list_account_records_response_account_record& operator=(const list_account_records_response_account_record& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_account_records_response_account_record& default_instance();

  void Swap(list_account_records_response_account_record* other);

  // implements Message ----------------------------------------------

  list_account_records_response_account_record* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_account_records_response_account_record& from);
  void MergeFrom(const list_account_records_response_account_record& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // required int32 limit = 2;
  inline bool has_limit() const;
  inline void clear_limit();
  static const int kLimitFieldNumber = 2;
  inline ::google::protobuf::int32 limit() const;
  inline void set_limit(::google::protobuf::int32 value);

  // required uint64 timestamp = 3;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  inline ::google::protobuf::uint64 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:tutorial.list_account_records_response.account_record)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_limit();
  inline void clear_has_limit();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 limit_;
  ::google::protobuf::uint64 timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_account_records_response_account_record* default_instance_;
};
// -------------------------------------------------------------------

class list_account_records_response : public ::google::protobuf::Message {
 public:
  list_account_records_response();
  virtual ~list_account_records_response();

  list_account_records_response(const list_account_records_response& from);

  inline list_account_records_response& operator=(const list_account_records_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_account_records_response& default_instance();

  void Swap(list_account_records_response* other);

  // implements Message ----------------------------------------------

  list_account_records_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_account_records_response& from);
  void MergeFrom(const list_account_records_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef list_account_records_response_account_record account_record;

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // repeated .tutorial.list_account_records_response.account_record records = 3;
  inline int records_size() const;
  inline void clear_records();
  static const int kRecordsFieldNumber = 3;
  inline const ::tutorial::list_account_records_response_account_record& records(int index) const;
  inline ::tutorial::list_account_records_response_account_record* mutable_records(int index);
  inline ::tutorial::list_account_records_response_account_record* add_records();
  inline const ::google::protobuf::RepeatedPtrField< ::tutorial::list_account_records_response_account_record >&
      records() const;
  inline ::google::protobuf::RepeatedPtrField< ::tutorial::list_account_records_response_account_record >*
      mutable_records();

  // @@protoc_insertion_point(class_scope:tutorial.list_account_records_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_desc();
  inline void clear_has_desc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  ::google::protobuf::RepeatedPtrField< ::tutorial::list_account_records_response_account_record > records_;
  ::google::protobuf::int32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_account_records_response* default_instance_;
};
// -------------------------------------------------------------------

class list_travel_records_request : public ::google::protobuf::Message {
 public:
  list_travel_records_request();
  virtual ~list_travel_records_request();

  list_travel_records_request(const list_travel_records_request& from);

  inline list_travel_records_request& operator=(const list_travel_records_request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_travel_records_request& default_instance();

  void Swap(list_travel_records_request* other);

  // implements Message ----------------------------------------------

  list_travel_records_request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_travel_records_request& from);
  void MergeFrom(const list_travel_records_request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mobile = 1;
  inline bool has_mobile() const;
  inline void clear_mobile();
  static const int kMobileFieldNumber = 1;
  inline const ::std::string& mobile() const;
  inline void set_mobile(const ::std::string& value);
  inline void set_mobile(const char* value);
  inline void set_mobile(const char* value, size_t size);
  inline ::std::string* mutable_mobile();
  inline ::std::string* release_mobile();
  inline void set_allocated_mobile(::std::string* mobile);

  // @@protoc_insertion_point(class_scope:tutorial.list_travel_records_request)
 private:
  inline void set_has_mobile();
  inline void clear_has_mobile();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mobile_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_travel_records_request* default_instance_;
};
// -------------------------------------------------------------------

class list_travel_records_response_travel_record : public ::google::protobuf::Message {
 public:
  list_travel_records_response_travel_record();
  virtual ~list_travel_records_response_travel_record();

  list_travel_records_response_travel_record(const list_travel_records_response_travel_record& from);

  inline list_travel_records_response_travel_record& operator=(const list_travel_records_response_travel_record& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_travel_records_response_travel_record& default_instance();

  void Swap(list_travel_records_response_travel_record* other);

  // implements Message ----------------------------------------------

  list_travel_records_response_travel_record* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_travel_records_response_travel_record& from);
  void MergeFrom(const list_travel_records_response_travel_record& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 stm = 1;
  inline bool has_stm() const;
  inline void clear_stm();
  static const int kStmFieldNumber = 1;
  inline ::google::protobuf::uint64 stm() const;
  inline void set_stm(::google::protobuf::uint64 value);

  // required uint32 duration = 2;
  inline bool has_duration() const;
  inline void clear_duration();
  static const int kDurationFieldNumber = 2;
  inline ::google::protobuf::uint32 duration() const;
  inline void set_duration(::google::protobuf::uint32 value);

  // required uint32 amount = 3;
  inline bool has_amount() const;
  inline void clear_amount();
  static const int kAmountFieldNumber = 3;
  inline ::google::protobuf::uint32 amount() const;
  inline void set_amount(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tutorial.list_travel_records_response.travel_record)
 private:
  inline void set_has_stm();
  inline void clear_has_stm();
  inline void set_has_duration();
  inline void clear_has_duration();
  inline void set_has_amount();
  inline void clear_has_amount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 stm_;
  ::google::protobuf::uint32 duration_;
  ::google::protobuf::uint32 amount_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_travel_records_response_travel_record* default_instance_;
};
// -------------------------------------------------------------------

class list_travel_records_response : public ::google::protobuf::Message {
 public:
  list_travel_records_response();
  virtual ~list_travel_records_response();

  list_travel_records_response(const list_travel_records_response& from);

  inline list_travel_records_response& operator=(const list_travel_records_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const list_travel_records_response& default_instance();

  void Swap(list_travel_records_response* other);

  // implements Message ----------------------------------------------

  list_travel_records_response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const list_travel_records_response& from);
  void MergeFrom(const list_travel_records_response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef list_travel_records_response_travel_record travel_record;

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // required double mileage = 3;
  inline bool has_mileage() const;
  inline void clear_mileage();
  static const int kMileageFieldNumber = 3;
  inline double mileage() const;
  inline void set_mileage(double value);

  // required double discharge = 4;
  inline bool has_discharge() const;
  inline void clear_discharge();
  static const int kDischargeFieldNumber = 4;
  inline double discharge() const;
  inline void set_discharge(double value);

  // required double calorie = 5;
  inline bool has_calorie() const;
  inline void clear_calorie();
  static const int kCalorieFieldNumber = 5;
  inline double calorie() const;
  inline void set_calorie(double value);

  // repeated .tutorial.list_travel_records_response.travel_record records = 6;
  inline int records_size() const;
  inline void clear_records();
  static const int kRecordsFieldNumber = 6;
  inline const ::tutorial::list_travel_records_response_travel_record& records(int index) const;
  inline ::tutorial::list_travel_records_response_travel_record* mutable_records(int index);
  inline ::tutorial::list_travel_records_response_travel_record* add_records();
  inline const ::google::protobuf::RepeatedPtrField< ::tutorial::list_travel_records_response_travel_record >&
      records() const;
  inline ::google::protobuf::RepeatedPtrField< ::tutorial::list_travel_records_response_travel_record >*
      mutable_records();

  // @@protoc_insertion_point(class_scope:tutorial.list_travel_records_response)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_desc();
  inline void clear_has_desc();
  inline void set_has_mileage();
  inline void clear_has_mileage();
  inline void set_has_discharge();
  inline void clear_has_discharge();
  inline void set_has_calorie();
  inline void clear_has_calorie();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  double mileage_;
  double discharge_;
  double calorie_;
  ::google::protobuf::RepeatedPtrField< ::tutorial::list_travel_records_response_travel_record > records_;
  ::google::protobuf::int32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_bike_2eproto();
  friend void protobuf_AssignDesc_bike_2eproto();
  friend void protobuf_ShutdownFile_bike_2eproto();

  void InitAsDefaultInstance();
  static list_travel_records_response* default_instance_;
};
// ===================================================================


// ===================================================================

// mobile_request

// required string mobile = 1;
inline bool mobile_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void mobile_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void mobile_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void mobile_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& mobile_request::mobile() const {
  return *mobile_;
}
inline void mobile_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void mobile_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void mobile_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* mobile_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* mobile_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void mobile_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// mobile_response

// required int32 code = 1;
inline bool mobile_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void mobile_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void mobile_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void mobile_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 mobile_response::code() const {
  return code_;
}
inline void mobile_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// required int32 icode = 2;
inline bool mobile_response::has_icode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void mobile_response::set_has_icode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void mobile_response::clear_has_icode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void mobile_response::clear_icode() {
  icode_ = 0;
  clear_has_icode();
}
inline ::google::protobuf::int32 mobile_response::icode() const {
  return icode_;
}
inline void mobile_response::set_icode(::google::protobuf::int32 value) {
  set_has_icode();
  icode_ = value;
}

// optional string data = 3;
inline bool mobile_response::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void mobile_response::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void mobile_response::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void mobile_response::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& mobile_response::data() const {
  return *data_;
}
inline void mobile_response::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void mobile_response::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void mobile_response::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* mobile_response::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* mobile_response::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void mobile_response::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// login_request

// required string mobile = 1;
inline bool login_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void login_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void login_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void login_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& login_request::mobile() const {
  return *mobile_;
}
inline void login_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void login_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void login_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* login_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* login_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void login_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 icode = 2;
inline bool login_request::has_icode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void login_request::set_has_icode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void login_request::clear_has_icode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void login_request::clear_icode() {
  icode_ = 0;
  clear_has_icode();
}
inline ::google::protobuf::int32 login_request::icode() const {
  return icode_;
}
inline void login_request::set_icode(::google::protobuf::int32 value) {
  set_has_icode();
  icode_ = value;
}

// -------------------------------------------------------------------

// login_response

// required int32 code = 1;
inline bool login_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void login_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void login_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void login_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 login_response::code() const {
  return code_;
}
inline void login_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string desc = 2;
inline bool login_response::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void login_response::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void login_response::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void login_response::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& login_response::desc() const {
  return *desc_;
}
inline void login_response::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void login_response::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void login_response::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* login_response::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* login_response::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void login_response::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// recharge_request

// required string mobile = 1;
inline bool recharge_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void recharge_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void recharge_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void recharge_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& recharge_request::mobile() const {
  return *mobile_;
}
inline void recharge_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void recharge_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void recharge_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* recharge_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* recharge_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void recharge_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 amount = 2;
inline bool recharge_request::has_amount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void recharge_request::set_has_amount() {
  _has_bits_[0] |= 0x00000002u;
}
inline void recharge_request::clear_has_amount() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void recharge_request::clear_amount() {
  amount_ = 0;
  clear_has_amount();
}
inline ::google::protobuf::int32 recharge_request::amount() const {
  return amount_;
}
inline void recharge_request::set_amount(::google::protobuf::int32 value) {
  set_has_amount();
  amount_ = value;
}

// -------------------------------------------------------------------

// recharge_response

// required int32 code = 1;
inline bool recharge_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void recharge_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void recharge_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void recharge_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 recharge_response::code() const {
  return code_;
}
inline void recharge_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string desc = 2;
inline bool recharge_response::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void recharge_response::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void recharge_response::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void recharge_response::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& recharge_response::desc() const {
  return *desc_;
}
inline void recharge_response::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void recharge_response::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void recharge_response::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* recharge_response::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* recharge_response::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void recharge_response::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 balance = 3;
inline bool recharge_response::has_balance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void recharge_response::set_has_balance() {
  _has_bits_[0] |= 0x00000004u;
}
inline void recharge_response::clear_has_balance() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void recharge_response::clear_balance() {
  balance_ = 0;
  clear_has_balance();
}
inline ::google::protobuf::int32 recharge_response::balance() const {
  return balance_;
}
inline void recharge_response::set_balance(::google::protobuf::int32 value) {
  set_has_balance();
  balance_ = value;
}

// -------------------------------------------------------------------

// account_balance_request

// required string mobile = 1;
inline bool account_balance_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void account_balance_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void account_balance_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void account_balance_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& account_balance_request::mobile() const {
  return *mobile_;
}
inline void account_balance_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void account_balance_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void account_balance_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* account_balance_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* account_balance_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void account_balance_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// account_balance_response

// required int32 code = 1;
inline bool account_balance_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void account_balance_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void account_balance_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void account_balance_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 account_balance_response::code() const {
  return code_;
}
inline void account_balance_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string desc = 2;
inline bool account_balance_response::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void account_balance_response::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void account_balance_response::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void account_balance_response::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& account_balance_response::desc() const {
  return *desc_;
}
inline void account_balance_response::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void account_balance_response::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void account_balance_response::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* account_balance_response::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* account_balance_response::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void account_balance_response::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 balance = 3;
inline bool account_balance_response::has_balance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void account_balance_response::set_has_balance() {
  _has_bits_[0] |= 0x00000004u;
}
inline void account_balance_response::clear_has_balance() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void account_balance_response::clear_balance() {
  balance_ = 0;
  clear_has_balance();
}
inline ::google::protobuf::int32 account_balance_response::balance() const {
  return balance_;
}
inline void account_balance_response::set_balance(::google::protobuf::int32 value) {
  set_has_balance();
  balance_ = value;
}

// -------------------------------------------------------------------

// list_account_records_request

// required string mobile = 1;
inline bool list_account_records_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_account_records_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_account_records_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_account_records_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& list_account_records_request::mobile() const {
  return *mobile_;
}
inline void list_account_records_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void list_account_records_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void list_account_records_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* list_account_records_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* list_account_records_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void list_account_records_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// list_account_records_response_account_record

// required int32 type = 1;
inline bool list_account_records_response_account_record::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_account_records_response_account_record::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_account_records_response_account_record::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_account_records_response_account_record::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 list_account_records_response_account_record::type() const {
  return type_;
}
inline void list_account_records_response_account_record::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// required int32 limit = 2;
inline bool list_account_records_response_account_record::has_limit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void list_account_records_response_account_record::set_has_limit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void list_account_records_response_account_record::clear_has_limit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void list_account_records_response_account_record::clear_limit() {
  limit_ = 0;
  clear_has_limit();
}
inline ::google::protobuf::int32 list_account_records_response_account_record::limit() const {
  return limit_;
}
inline void list_account_records_response_account_record::set_limit(::google::protobuf::int32 value) {
  set_has_limit();
  limit_ = value;
}

// required uint64 timestamp = 3;
inline bool list_account_records_response_account_record::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void list_account_records_response_account_record::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void list_account_records_response_account_record::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void list_account_records_response_account_record::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 list_account_records_response_account_record::timestamp() const {
  return timestamp_;
}
inline void list_account_records_response_account_record::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// -------------------------------------------------------------------

// list_account_records_response

// required int32 code = 1;
inline bool list_account_records_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_account_records_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_account_records_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_account_records_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 list_account_records_response::code() const {
  return code_;
}
inline void list_account_records_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string desc = 2;
inline bool list_account_records_response::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void list_account_records_response::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void list_account_records_response::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void list_account_records_response::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& list_account_records_response::desc() const {
  return *desc_;
}
inline void list_account_records_response::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void list_account_records_response::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void list_account_records_response::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* list_account_records_response::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* list_account_records_response::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void list_account_records_response::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .tutorial.list_account_records_response.account_record records = 3;
inline int list_account_records_response::records_size() const {
  return records_.size();
}
inline void list_account_records_response::clear_records() {
  records_.Clear();
}
inline const ::tutorial::list_account_records_response_account_record& list_account_records_response::records(int index) const {
  return records_.Get(index);
}
inline ::tutorial::list_account_records_response_account_record* list_account_records_response::mutable_records(int index) {
  return records_.Mutable(index);
}
inline ::tutorial::list_account_records_response_account_record* list_account_records_response::add_records() {
  return records_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tutorial::list_account_records_response_account_record >&
list_account_records_response::records() const {
  return records_;
}
inline ::google::protobuf::RepeatedPtrField< ::tutorial::list_account_records_response_account_record >*
list_account_records_response::mutable_records() {
  return &records_;
}

// -------------------------------------------------------------------

// list_travel_records_request

// required string mobile = 1;
inline bool list_travel_records_request::has_mobile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_travel_records_request::set_has_mobile() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_travel_records_request::clear_has_mobile() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_travel_records_request::clear_mobile() {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    mobile_->clear();
  }
  clear_has_mobile();
}
inline const ::std::string& list_travel_records_request::mobile() const {
  return *mobile_;
}
inline void list_travel_records_request::set_mobile(const ::std::string& value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void list_travel_records_request::set_mobile(const char* value) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(value);
}
inline void list_travel_records_request::set_mobile(const char* value, size_t size) {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  mobile_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* list_travel_records_request::mutable_mobile() {
  set_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    mobile_ = new ::std::string;
  }
  return mobile_;
}
inline ::std::string* list_travel_records_request::release_mobile() {
  clear_has_mobile();
  if (mobile_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mobile_;
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void list_travel_records_request::set_allocated_mobile(::std::string* mobile) {
  if (mobile_ != &::google::protobuf::internal::kEmptyString) {
    delete mobile_;
  }
  if (mobile) {
    set_has_mobile();
    mobile_ = mobile;
  } else {
    clear_has_mobile();
    mobile_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// list_travel_records_response_travel_record

// required uint64 stm = 1;
inline bool list_travel_records_response_travel_record::has_stm() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_travel_records_response_travel_record::set_has_stm() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_travel_records_response_travel_record::clear_has_stm() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_travel_records_response_travel_record::clear_stm() {
  stm_ = GOOGLE_ULONGLONG(0);
  clear_has_stm();
}
inline ::google::protobuf::uint64 list_travel_records_response_travel_record::stm() const {
  return stm_;
}
inline void list_travel_records_response_travel_record::set_stm(::google::protobuf::uint64 value) {
  set_has_stm();
  stm_ = value;
}

// required uint32 duration = 2;
inline bool list_travel_records_response_travel_record::has_duration() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void list_travel_records_response_travel_record::set_has_duration() {
  _has_bits_[0] |= 0x00000002u;
}
inline void list_travel_records_response_travel_record::clear_has_duration() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void list_travel_records_response_travel_record::clear_duration() {
  duration_ = 0u;
  clear_has_duration();
}
inline ::google::protobuf::uint32 list_travel_records_response_travel_record::duration() const {
  return duration_;
}
inline void list_travel_records_response_travel_record::set_duration(::google::protobuf::uint32 value) {
  set_has_duration();
  duration_ = value;
}

// required uint32 amount = 3;
inline bool list_travel_records_response_travel_record::has_amount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void list_travel_records_response_travel_record::set_has_amount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void list_travel_records_response_travel_record::clear_has_amount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void list_travel_records_response_travel_record::clear_amount() {
  amount_ = 0u;
  clear_has_amount();
}
inline ::google::protobuf::uint32 list_travel_records_response_travel_record::amount() const {
  return amount_;
}
inline void list_travel_records_response_travel_record::set_amount(::google::protobuf::uint32 value) {
  set_has_amount();
  amount_ = value;
}

// -------------------------------------------------------------------

// list_travel_records_response

// required int32 code = 1;
inline bool list_travel_records_response::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void list_travel_records_response::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void list_travel_records_response::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void list_travel_records_response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 list_travel_records_response::code() const {
  return code_;
}
inline void list_travel_records_response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string desc = 2;
inline bool list_travel_records_response::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void list_travel_records_response::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void list_travel_records_response::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void list_travel_records_response::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& list_travel_records_response::desc() const {
  return *desc_;
}
inline void list_travel_records_response::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void list_travel_records_response::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void list_travel_records_response::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* list_travel_records_response::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* list_travel_records_response::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void list_travel_records_response::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required double mileage = 3;
inline bool list_travel_records_response::has_mileage() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void list_travel_records_response::set_has_mileage() {
  _has_bits_[0] |= 0x00000004u;
}
inline void list_travel_records_response::clear_has_mileage() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void list_travel_records_response::clear_mileage() {
  mileage_ = 0;
  clear_has_mileage();
}
inline double list_travel_records_response::mileage() const {
  return mileage_;
}
inline void list_travel_records_response::set_mileage(double value) {
  set_has_mileage();
  mileage_ = value;
}

// required double discharge = 4;
inline bool list_travel_records_response::has_discharge() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void list_travel_records_response::set_has_discharge() {
  _has_bits_[0] |= 0x00000008u;
}
inline void list_travel_records_response::clear_has_discharge() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void list_travel_records_response::clear_discharge() {
  discharge_ = 0;
  clear_has_discharge();
}
inline double list_travel_records_response::discharge() const {
  return discharge_;
}
inline void list_travel_records_response::set_discharge(double value) {
  set_has_discharge();
  discharge_ = value;
}

// required double calorie = 5;
inline bool list_travel_records_response::has_calorie() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void list_travel_records_response::set_has_calorie() {
  _has_bits_[0] |= 0x00000010u;
}
inline void list_travel_records_response::clear_has_calorie() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void list_travel_records_response::clear_calorie() {
  calorie_ = 0;
  clear_has_calorie();
}
inline double list_travel_records_response::calorie() const {
  return calorie_;
}
inline void list_travel_records_response::set_calorie(double value) {
  set_has_calorie();
  calorie_ = value;
}

// repeated .tutorial.list_travel_records_response.travel_record records = 6;
inline int list_travel_records_response::records_size() const {
  return records_.size();
}
inline void list_travel_records_response::clear_records() {
  records_.Clear();
}
inline const ::tutorial::list_travel_records_response_travel_record& list_travel_records_response::records(int index) const {
  return records_.Get(index);
}
inline ::tutorial::list_travel_records_response_travel_record* list_travel_records_response::mutable_records(int index) {
  return records_.Mutable(index);
}
inline ::tutorial::list_travel_records_response_travel_record* list_travel_records_response::add_records() {
  return records_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tutorial::list_travel_records_response_travel_record >&
list_travel_records_response::records() const {
  return records_;
}
inline ::google::protobuf::RepeatedPtrField< ::tutorial::list_travel_records_response_travel_record >*
list_travel_records_response::mutable_records() {
  return &records_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bike_2eproto__INCLUDED
